import './scss/main.scss';
import './scss/header.scss';
import './scss/services.scss';
import './scss/portfolio.scss';
import './scss/about.scss';
import './scss/info.scss';
import './scss/our-team.scss';
import './scss/testimonials.scss';
import './scss/contacts.scss';
